apiVersion: v1
kind: Service
metadata:
  name: sql-service
  labels:
    app: sql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30012
    protocol: TCP
  selector:
    app: sql